version: "3.9"

services:
  api:
    build:
      context: ./backend
      dockerfile: deployment/Dockerfile
    environment:
      - POSTGRES_HOST=database
      - POSTGRES_PORT=5432
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_NAME=${POSTGRES_DATABASE}
    ports:
      - 4001:4001
    depends_on:
      - database
    env_file:
      - .env

  web:
    build:
      context: ./frontend
      dockerfile: deployment/Dockerfile
    ports:
      - 80:80
    depends_on:
      - api

  database:
    image: postgres:15.3
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DATABASE}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - ./postgres:/var/lib/postgresql/data
    env_file:
      - .env

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
  jenkins_home:
